#+title: What Is Iso Iec 27001
#+author: gabriel

* purpose
Norma internacional para estabelecer, implementar, manter e aprimorar um sistema de gestão de segurança da informação (SGSI)

Publicada pela ISO em 2005, revisada em 2013 e novamente em 2022

A estrutura adota uma abordagem baseada em riscos para a gestão de riscos de segurança da informação

- confidencialidade, integridade, disponibilidade

Oferece uma abordagem sistemática e repetível para o gerenciamento de dados sensíveis e concentra-se na mitigação de riscos associados a ameaças e vulnerabilidades.

- Permite que as organizações identifiquem e mitiguem riscos.

- Cumpram requisitos regulatórios ou contratuais.

- Aprimoram as práticas de segurança da informação.


* 2022 revision
Controles atualizados no anexo A para lidar com as ameaças de cibersegurança em constante evolução.

Adicionados 11 novos controles, incluindo inteligência de ameaças e prevenção de vazamento de dados.

Estrutura alinhada com a estrutura harmonizada da ISO (anexo SL) para melhor integração com outras normas ISO.

* Plan Do Check Act PDCA
*plan* ->
- Estabelecer políticas, recursos e objetivos do SGSI (Sistema de Gestão de Segurança da Informação)

*do* ->
- Implementar avaliações, tratamentos e controles de risco

*check* ->
- Monitorar as principais métricas para garantir a eficácia

*act* ->
- Melhorar abordando as não conformidades
