#+title: Audit Team Roles
#+author: gabriel

* intro
Clearyl defined roles and responsibilities are essential

A composição da equipe de auditoria depende de:
- tamanho e complexidade da empresa auditada
- escopo da auditoria

A competência coletiva é necessária para avaliar o SGSI (Sistema de Gestão de Segurança da Informação) e os controles de segurança

*Ponto-chave* --> Compreender as funções da equipe auxilia na condução adequada das auditorias, seja você iniciante ou esteja em transição para auditorias ISO

* lead auditor
*Role* --> Lidera o processo de auditoria, tanto no contato com o cliente quanto com a equipe
- Planeja a auditoria (tempo, escopo, amostragem, equipe, cronograma, orçamento)
- Realiza reuniões de abertura e entrevistas com as partes interessadas da empresa auditada
- Revisa as evidências, determina as não conformidades e finaliza o relatório de auditoria

*Competency* --> Strong ISO 27001 knowledge and  understanding of accreditation requirements

* auditor
*Role* --> Apoia o auditor líder e realiza atividades de auditoria
- Realiza entrevistas com as partes interessadas (por exemplo, líderes, gerentes, responsáveis ​​pelos controles)
- Revisa as evidências documentadas para conformidade com a ISO 27001
- Elabora as conclusões iniciais, identifica as não conformidades e acompanha os itens de acompanhamento.

*Competency* --> knowledge of ISO 27001 and audit techniques, organizational and analytical skills

* technical expert or guide
*Role* --> Fornece conhecimento especializado em domínios técnicos específicos.
- Avalia controles específicos do Anexo A (por exemplo, segurança na nuvem, criptografia, redes).
- Orienta a equipe de auditoria em questões de conformidade técnica.
- Pode auxiliar na tradução para idiomas com pessoas que não falam o idioma nativo.

*Competency* --> subject matter or language-specific only

* observer
*Role* --> Observa a auditoria para aprendizado, supervisão ou representação das partes interessadas.
- Adquire experiência ou supervisiona a auditoria.
- Representa as partes interessadas, como órgãos reguladores.
- Mantém a confidencialidade e a imparcialidade.
- Não emite opinião sobre as conclusões da auditoria.

*Competency* --> none required, but the lead auditor should brief the observer beforehand

** importance of audit team composition
- *Consistency* --> defined roles ensure audits achieve objectives across clients
- *Efficiency* --> clear roles enable effective collaboration and work distribution
- *Depth* --> a well-composed team with the right number of auditors and technical expertise ensures thorough audits
